on: [push]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    name: Build and run Docker image
    steps:
        
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Build Docker image
        run: docker build -t hello-image < Dockerfile
        
      - name: Run image
        run: docker run --rm hello-image